### ISSUE TITLE
Having issues with opening DiscordAddonRimworldTogether(solved)

### ISSUE THREAD

**Issue by vasyly8754** [nay-cat/Rimworld-Together-DiscordAddon#1]
for some reason cant open DiscordAddonRimworldTogether, antivirus is off and Net framework 6 is downloaded(as seven), maybe i still miss some libraries?

**Comment by nay-cat** [comment]
Some crashdump in AppData\Local\CrashDumps?

**Comment by vasyly8754** [comment]
> What windows version are you using?

I use windows 10 home
19045.3570

**Comment by vasyly8754** [comment]
> Some crashdump in AppData\Local\CrashDumps?

No, there aren't

**Comment by vasyly8754** [comment]
also my .net version is .NET Runtime 6.0.25(if it makes difference)

**Comment by vasyly8754** [comment]
Nevermind, i just had to download x64 version of .dotnet, my bad :(
